"""initial schema

Revision ID: 3927ddd8cce3
Revises: 
Create Date: 2026-08-19 16:45:52.193609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3927ddd8cce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_bays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bay_number', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('current_trainset', sa.String(), nullable=True),
    sa.Column('available_manpower', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_bays_bay_number'), 'cleaning_bays', ['bay_number'], unique=True)
    op.create_index(op.f('ix_cleaning_bays_id'), 'cleaning_bays', ['id'], unique=False)
    op.create_table('cleaning_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('current_assignment', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_teams_id'), 'cleaning_teams', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_teams_team_name'), 'cleaning_teams', ['team_name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('trainsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('fitness_valid', sa.Boolean(), nullable=True),
    sa.Column('job_card_open', sa.Boolean(), nullable=True),
    sa.Column('branding', sa.String(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('needs_deep_clean', sa.Boolean(), nullable=True),
    sa.Column('deep_clean_complexity', sa.String(), nullable=True),
    sa.Column('estimated_clean_time', sa.Integer(), nullable=True),
    sa.Column('required_manpower', sa.Integer(), nullable=True),
    sa.Column('sensor_aggregate', sa.Float(), nullable=True),
    sa.Column('days_since_inspection', sa.Integer(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainsets_code'), 'trainsets', ['code'], unique=True)
    op.create_index(op.f('ix_trainsets_id'), 'trainsets', ['id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('trainset_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('needs_deep_clean', sa.Boolean(), nullable=True),
    sa.Column('maintenance_priority', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.String(), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('maintenance_score', sa.Float(), nullable=True),
    sa.Column('fitness_status', sa.String(), nullable=True),
    sa.Column('assigned_bay', sa.String(), nullable=True),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('manpower', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_id'), 'plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_plan_items_trainset_code'), 'plan_items', ['trainset_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_items_trainset_code'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_trainsets_id'), table_name='trainsets')
    op.drop_index(op.f('ix_trainsets_code'), table_name='trainsets')
    op.drop_table('trainsets')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_cleaning_teams_team_name'), table_name='cleaning_teams')
    op.drop_index(op.f('ix_cleaning_teams_id'), table_name='cleaning_teams')
    op.drop_table('cleaning_teams')
    op.drop_index(op.f('ix_cleaning_bays_id'), table_name='cleaning_bays')
    op.drop_index(op.f('ix_cleaning_bays_bay_number'), table_name='cleaning_bays')
    op.drop_table('cleaning_bays')
    # ### end Alembic commands ###
